### ISSUE TITLE
Ability for the following messages to be configurable/formatted nicely 

### ISSUE THREAD

**Issue by HackuJacku** [Pixelmon-Development/ForgeEconomies#1]
- Reload
- Admin: player has insufficient funds
- Admin: set balance

**Comment by danorris709** [comment]
Is it important for these messages to be configurable given they're only viewed by admins?

**Comment by HackuJacku** [comment]
No but would be nice if they provided the full command syntax

**Comment by danorris709** [comment]
Added in latest
