### ISSUE TITLE
Pixelmon Eco Integration

### ISSUE THREAD

**Issue by austin4195** [Pixelmon-Development/ForgeEconomies#16]
### Issue Present

As it stands, ForgeEconomies doesn't seem to play nicely with Pixelmon Reforged in terms of economy. Reforged makes use of its own internal economy engine. This internal economy can be bridged into Sponge Economy through the Economy Bridge sidemod on the website. When replacing Economy Lite with ForgeEconomies and the Sponge Bridge, the following scenario is how it should operate.

<img width="566" alt="Screen Shot 2021-09-13 at 1 27 44 PM" src="https://user-images.githubusercontent.com/359009/133175133-98acfd26-4e5f-45e5-8502-add5a55e9df7.png">

What is found is that ForgeEconomies does successfully register as a Sponge Economy mod thanks to the bridge and can successfully increase or decrease balances which can be reflected in ForgeEconomies internal commands. The issue that arises is that there is a disconnect in the Pixelmon Economy Bridge so the Sponge Balance ≠ Pixelmon Balance.

### Solutions

Option 1: Implement a Reforged Bridge. This reforged bridge would directly interface ForgeEconomies with the Reforged internal economy system. The Sponge Bridge would then facilitate the use of that balance through the Sponge Economy system and any plugins that would make use of that. The benefit to this is that the Spigot Bridge would also have its stuff streamlined. There would no longer be a need for EcoBridgeSpigot or EconomyBridge since ForgeEconomies would interface directly with Reforged and would interface with Sponge Economy or Vault through the Sponge Bridge and Spigot Bridge respectively. A diagram of this proposal can be found here.

<img width="528" alt="Screen Shot 2021-09-13 at 1 26 36 PM" src="https://user-images.githubusercontent.com/359009/133175135-825998f0-ae4a-4ca9-ba6c-6fedf2a074f1.png">

Option 2: Identify the issue within the EconomyBridge sidemod.

**Comment by austin4195** [comment]
Resolving this with a Reforged Bridge might also fix the %reforged_balance% placeholder as it would now be synced with Forge Economies as well as Sponge Economy.

**Comment by danorris709** [comment]
This issue should be resolved in the newer versions of the sponge bridge and I am actively dealing with the Sponge PAPI issues
